#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages

name: Deploy to Github pages

on:
  push:
    branches:
      - docs

jobs:
  deploy-gh-pages:
    name: Deploy SDK TypeDoc and Code Coverage to Github Pages.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install # TODO: cache
      - run: yarn docs && yarn test:coverage
      - run: touch docs/.nojekyll
      - name: Deploy docs ðŸš€
        if: ${{ env.DEPLOYMENT_STATUS }} == "success"
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          COMMIT-MESSAGE: "Deployed SDK Docs & Code Coverage to Github Pages (https://monerium.github.io/sdk)"
      # - name: Deploy code coverage ðŸš€
      #   uses: JamesIves/github-pages-deploy-action@v4.2.5
      #   with:
      #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages # The branch the action should deploy to.
      #     FOLDER: coverage/lcov-report # The folder the action should deploy.
      #     CLEAN: true # Automatically remove deleted files from the deploy branch
      #     COMMIT-MESSAGE: "Deployed SDK Docs & Code Coverage to Github Pages (https://monerium.github.io/sdk)"
      #     TARGET-FOLDER: coverage
